# Stage 1: Build Angular App
FROM node:18 AS builder

WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build --configuration production

# Stage 2: Serve via nginx
FROM nginx:alpine

COPY --from=builder /app/dist/conduit-frontend /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]